#Bitcoin RPC configuration
BTC_PROTOCOL: "http"
BTC_PORT: 18332
ZMQ_PORT: 49332
BTC_HOST: "bitcoind-testnet4"
BTC_RPC_USERNAME: "user1"
BTC_RPC_PASSWORD: "ThisIsAPassword"
BTC_NETWORK: "testnet4"

NOSTR_RELAYS: ["wss://lightningrelay.com", "wss://relay.damus.io", "wss://nostr.einundzwanzig.space", "wss://relay01.lnfi.network/", "wss://njump.me/", "wss://fiatjaf.com/"]

#STARKNET:
#  #Enable/disable individual watchtowers
#  WATCHTOWERS:
#    LEGACY_SWAPS: true
#    SPV_SWAPS: true
#    HTLC_SWAPS: true
#
#  #Starknet RPC URL to use, it is recommended to use a dedicated RPC endpoint
#  RPC_URL: ""
#  #Can also optionally specify an additional WS URL - allows for faster swap processing
#  #WS_URL: ""
#  #CLI - command line interface config
#  CLI_ADDRESS: "0.0.0.0"
#  CLI_PORT: 40130
#  #Maximum gas price
#  MAX_L1_FEE_GWEI: 20000000
#  MAX_L2_FEE_GWEI: 4000000
#  MAX_L1_DATA_FEE_GWEI: 10000000
#  #Starknet chain to use
#  CHAIN: "SEPOLIA"
#  #File with the wallet mnemonic seed
#  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"

CITREA:
  #Enable/disable individual watchtowers
  WATCHTOWERS:
    LEGACY_SWAPS: true
    SPV_SWAPS: true
    HTLC_SWAPS: true

  #Citrea RPC URL, can either be an http or ws RPC
  RPC_URL: "https://rpc.testnet.citrea.xyz"
  #Maximum block range that the underlying RPC provider supports
  MAX_LOGS_BLOCK_RANGE: 900
  #CLI - command line interface config
  CLI_ADDRESS: "0.0.0.0"
  CLI_PORT: 40150
  #Fees
  MAX_FEE_GWEI: 2
  FEE_TIP_GWEI: 0.001
  #Botanix chain
  CHAIN: "TESTNET4"

  #File with wallet mnemonic seed
  MNEMONIC_FILE: "/mnt/share/wallet/mnemonic.txt"
